# Generated by Django 2.2.7 on 2019-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(default='강남구', max_length=100),
        ),
    ]
